backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "مقالات"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "عنوان", name: "title", widget: "string" }
      - { label: "تاریخ انتشار", name: "date", widget: "datetime" }
      - { label: "تصویر شاخص", name: "thumbnail", widget: "image", required: false }
      - { label: "خلاصه", name: "description", widget: "text" }
      - { label: "متن اصلی", name: "body", widget: "markdown" }
